Repository rvm/rvm, pull requests merged in 2018-12, with the labels that each got.

#4516 Add support for mruby 2.0.0
  CHANGELOG.md
  config/db
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: interpreter: mruby

#4517 Add support for mruby 1.4.1
  CHANGELOG.md
  config/known
  config/md5
  config/sha512
Labels: interpreter: mruby

#4519 Mention pkuczynski gpg key in docs and cli
  CHANGELOG.md
  binscripts/rvm-installer
  binscripts/rvm-installer.asc
  docs/gpg.md
  scripts/functions/cli
Labels: documentation

#4501 Remove gcc in favour of Command Line Tools on macOS Mojave
  CHANGELOG.md
  scripts/functions/requirements/osx_brew
Labels: bug

#4458 Improve gpg signature verification docs
  docs/gpg.md
Labels: documentation

#4328 Fix Rubinius build on macOS with Homebrew
  CHANGELOG.md
  scripts/functions/manage/rubinius
  scripts/functions/requirements/osx_brew
Labels: feature, interpreter: rubinius, work in progress

#4524 Fix Linux Mint 19 dependencies
  CHANGELOG.md
  scripts/functions/requirements/mint
Labels: platform: linux

#4523 Release procedure description
  docs/gpg.md
  docs/release-procedure.md
Labels: documentation

#4531 Fix return code in signature check function (#4530)
  CHANGELOG.md
  scripts/functions/cli
Labels: bug, fixed

#4534 Check `stable` branch to establish the latest version
  CHANGELOG.md
  scripts/functions/version
Labels: bug

#4550 Remove reference to keys.gnupg.net in favour of pool.sks-keyservers.net
  .travis.yml
  CHANGELOG.md
  binscripts/rvm-installer
  binscripts/rvm-installer.asc
  scripts/functions/cli
Labels: bug, documentation

#4551 Fix Homebrew docs links
  CHANGELOG.md
  scripts/functions/requirements/osx_brew
Labels: documentation

#4556 Add support for gcc 8 with Homebrew and drop gcc older then 4.9
  CHANGELOG.md
  scripts/functions/requirements/osx_brew
Labels: platform: osx

#4557 Use gcc from XCode for macOS Mojave (10.14)
  CHANGELOG.md
  scripts/functions/requirements/osx_brew
Labels: bug

#4558 Stop uninstalling gcc from Homebrew
  CHANGELOG.md
  scripts/functions/requirements/osx_brew
Labels: bug
