Repository rvm/rvm, pull requests merged in 2019-07, with the labels that each got.

#4642 Use newer llvm on Mint 19.1+
  CHANGELOG.md
  scripts/functions/requirements/mint
Labels: bug

#4612 Preserve the environment setting in rvmrc and .rvmrc in multi or mixed mode
  CHANGELOG.md
  binscripts/rvm-installer.asc
  scripts/functions/installer
Labels: bug

#4735 Add support for Rubinius 4.4 and 4.5
  CHANGELOG.md
  config/known
  config/known_strings
Labels: interpreter: rubinius

#4743 Ignore aliases when using `ls` command
  CHANGELOG.md
  scripts/functions/gemset
  scripts/functions/support
Labels: bug, fixed
