Repository rvm/rvm, pull requests merged in 2019-08, with the labels that each got.

#4744 Implement new __rvm_ls across the whole app
  bin/rvmsudo
  scripts/extras/chruby.sh
  scripts/extras/completion.bash
  scripts/functions/build_config_system
  scripts/functions/manage/ree
  scripts/functions/requirements/netbsd
  scripts/functions/requirements/osx_brew
  scripts/info
  scripts/maglev
  scripts/mount
Labels: feature

#4757 Restore rvm test
  HACKING.md
  rvm-test/.gitignore
  rvm-test/.travis.yml
  rvm-test/.versions.conf
  rvm-test/Gemfile
  rvm-test/README.md
  rvm-test/fast/alias_comment_test.sh
  rvm-test/fast/current_and_list_comment_test.sh
  rvm-test/fast/do_comment_test.sh
  rvm-test/fast/env_comment_test.sh
  rvm-test/fast/exports_comment_test.sh
  rvm-test/fast/gem-bundle_comment_test.sh
  rvm-test/fast/gemfile_comment_test.sh
  rvm-test/fast/gemset-copy_comment_test.sh
  rvm-test/fast/gemsets_comment_test.sh
  rvm-test/fast/globalcache_comment_test.sh
  rvm-test/fast/remote_comment_test.sh
  rvm-test/fast/ruby-version_comment_test.sh
  rvm-test/fast/rvm-prompt_comment_test.sh
  rvm-test/fast/rvm-shell_comment_test.sh
  rvm-test/fast/rvmrc-create_comment_test.sh
  rvm-test/fast/rvmrc-warning_comment_test.sh
  rvm-test/fast/rvmrc_comment_test.sh
  rvm-test/fast/use_comment_test.sh
  rvm-test/fast/versions.conf_comment_test.sh
  rvm-test/fast/wrapper_comment_test.sh
  rvm-test/long/jruby_comment_test.sh
  rvm-test/long/named_ruby_and_gemsets_comment_test.sh
  rvm-test/long/rubinius_comment_test.sh
  rvm-test/long/ruby-1.8.7_comment_test.sh
  rvm-test/long/ruby-1.9.3_comment_test.sh
  rvm-test/long/truffleruby_comment_test.sh
Labels: fixed

#4760 Guard to prevent removal of the entire path in __rvm_remove_from_path
  CHANGELOG.md
  scripts/functions/utility
Labels: bug, fixed

#4761 Add TruffleRuby 19.2.0
  CHANGELOG.md
  config/db
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: interpreter: truffleruby

#4767 Adds support for Ruby 2.4.7 and 2.5.6
  CHANGELOG.md
  CONTRIBUTING.md
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: feature

#4768 Add support for Ruby 2.6.4
  CHANGELOG.md
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: feature

#4769 Fixes checksums for ruby 2.6.4
  CHANGELOG.md
  config/md5
  config/sha512
Labels: bug

#4771 Fixes checksums for Ruby 2.4.7 and 2.5.6
  CHANGELOG.md
  config/md5
  config/sha512
Labels: bug

#4772 added railsexpress patches for 2.4.6, 2.5.6 and 2.6.4
  CHANGELOG.md
  patchsets/ruby/2.4.6/railsexpress
  patchsets/ruby/2.5.6/railsexpress
  patchsets/ruby/2.6.4/railsexpress
  patchsets/ruby/2.6/head/railsexpress
Labels: feature
