Repository rvm/rvm, pull requests merged in 2019-11, with the labels that each got.

#4812 Add support for jruby 9.2.9.0
  CHANGELOG.md
  config/db
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: interpreter: jruby

#4816 Add support for mruby 2.1.0
  CHANGELOG.md
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: interpreter: mruby

#4817 Add support for Ruby 2.7.0-preview3
  CHANGELOG.md
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: feature
