Repository rvm/rvm, pull requests merged in 2019-09, with the labels that each got.

#4778 Fix string corruption bug on railsexpress ruby 2.6.4
  CHANGELOG.md
  patchsets/ruby/2.6.4/railsexpress
Labels: feature

#4779 Add support for Rubinius 4.6
  CHANGELOG.md
  config/known
  config/known_strings
Labels: interpreter: rubinius

#4784 Add TruffleRuby 19.2.0.1
  CHANGELOG.md
  config/db
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: interpreter: truffleruby

#4780 Patch the 2.6.4 string corruption bug
  CHANGELOG.md
  config/db
  patches/ruby/2.6.4/fix_string_corruption.patch
  patchsets/ruby/2.6.4/default
Labels: feature

#4789 Adding Ubuntu 18.04 x64 binaries for rubies 2.4.7, 2.5.6 and 2.6.4 (#4788)
  CHANGELOG.md
  config/md5
  config/remote
  config/sha512
Labels: binary, feature
