Repository rvm/rvm, pull requests merged in 2020-11, with the labels that each got.

#5001 Fix broken mergeable config
  .github/mergeable.yml
  CHANGELOG.md
Labels: bug

#5005 Add TruffleRuby 20.3.0
  .travis.yml
  CHANGELOG.md
  config/db
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: interpreter: truffleruby

#4995 Update brew list command to remove deprecation warning
  CHANGELOG.md
  scripts/functions/requirements/osx_brew
Labels: fixed
