Repository rvm/rvm, pull requests merged in 2020-04, with the labels that each got.

#4900 Railsexpress patches for 2.5.8, 2.6.6 and 2.7.1
  CHANGELOG.md
  patchsets/ruby/2.5.8/railsexpress
  patchsets/ruby/2.6.6/railsexpress
  patchsets/ruby/2.7.1/railsexpress
  patchsets/ruby/2.7/head/railsexpress
Labels: feature

#4905 Ubuntu 18.04 binaries for 2.4.10, 2.5.8, 2.6.6 and 2.7.1 (#4904)
  CHANGELOG.md
  config/md5
  config/remote
  config/sha512
Labels: binary

#4909 Add support for mruby 2.1.1-rc
  CHANGELOG.md
  config/known_strings
  config/md5
  config/sha512
Labels: interpreter: mruby

#4910 Add support for truffleruby 19.0.2, 19.1.1, 19.2.1, 19.3.0.2
  CHANGELOG.md
  config/known_strings
  config/md5
  config/sha512
Labels: interpreter: truffleruby

#4912 Fix mergeable settings failing the PR
  .github/mergeable.yml
Labels: bug
