Repository rvm/rvm, pull requests merged in 2020-10, with the labels that each got.

#4989 Added ruby 2.7.2 x64 binaries for linux systems
  CHANGELOG.md
  config/md5
  config/remote
  config/sha512
Labels: binary

#4987 Recognize `3*` as CRuby version number
  scripts/functions/selector_parse
Labels: feature

#4997 Added libssl dependency also to ree 1.8
  CHANGELOG.md
  scripts/functions/requirements/ubuntu
Labels: bug
