Repository rvm/rvm, pull requests merged in 2020-02, with the labels that each got.

#4871 Add support for truffleruby-head
  CHANGELOG.md
  rvm-test/long/truffleruby_comment_test.sh
  scripts/functions/manage/base_fetch
  scripts/functions/selector_interpreters
Labels: interpreter: truffleruby

#4872 Do not warn if using a development version newer than the latest release
  CHANGELOG.md
  scripts/functions/cli
Labels: bug

#4877 Add support for JRuby 9.2.10.0
  CHANGELOG.md
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: interpreter: jruby
