Repository rvm/rvm, pull requests merged in 2021-07, with the labels that each got.

#5098 Add support for Ruby 2.6.8, 2.7.4, 3.0.2
  CHANGELOG.md
  config/db
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: feature

#5103 Add TruffleRuby 21.2.0
  CHANGELOG.md
  config/db
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: interpreter: truffleruby

#5040 GitHub Actions
  .github/workflows/gpg_signature.yml
  .github/workflows/specs.yml
  .travis.yml
Labels: platform: linux

#5101 Fix Termux
  CHANGELOG.md
  scripts/functions/notes/warnings/warning_zsh
  scripts/functions/requirements/termux
  scripts/functions/utility_system
Labels: bug

#5104 Improve GitHub Actions
  .github/workflows/gpg_signature.yml
  .github/workflows/specs.yml
Labels: CI

#5105 Small cleanup after removig Travis and merging rvm-test repo
  .gems
  rvm-test/.gitignore
  rvm-test/.travis.yml
  rvm-test/README.md
Labels: CI

#5107 Remove Travis badges
  HACKING.md
  README.md
Labels: documentation

#5106 Move all tests into a common location
  .github/workflows/specs.yml
  HACKING.md
  rvm-test-rvm1/exports_comment_test.sh
  tests/.versions.conf
  tests/Gemfile
  tests/README.md
  tests/fast/alias_comment_test.sh
  tests/fast/array_comment_test.sh
  tests/fast/bundler_cd_hook_comment_test.sh
  tests/fast/current_and_list_comment_test.sh
  tests/fast/do_comment_test.sh
  tests/fast/env_comment_test.sh
  tests/fast/exports_comment_test.sh
  tests/fast/gem-bundle_comment_test.sh
  tests/fast/gemfile_comment_test.sh
  tests/fast/gemset-copy_comment_test.sh
  tests/fast/gemsets_comment_test.sh
  tests/fast/globalcache_comment_test.sh
  tests/fast/load_ruby-version_comment_test.sh
  tests/fast/path_mismatch_comment_test.sh
  tests/fast/pwd_cd_hook_comment_test.sh
  tests/fast/remote_comment_test.sh
  tests/fast/ruby-env_comment_test.sh
  tests/fast/ruby-version_comment_test.sh
  tests/fast/rvm-prompt_comment_test.sh
  tests/fast/rvm-shell_comment_test.sh
  tests/fast/rvm-user_comment_test.sh
  tests/fast/rvm_project_rvmrc_comment_test.sh
  tests/fast/rvmrc-create_comment_test.sh
  tests/fast/rvmrc-warning_comment_test.sh
  tests/fast/rvmrc_comment_test.sh
  tests/fast/use_comment_test.sh
  tests/fast/version_compare_comment_test.sh
  tests/fast/versions.conf_comment_test.sh
  tests/fast/wrapper_comment_test.sh
  tests/long/jruby_comment_test.sh
  tests/long/named_ruby_and_gemsets_comment_test.sh
  tests/long/rubinius_comment_test.sh
  tests/long/ruby-1.8.7_comment_test.sh
  tests/long/ruby-1.9.3_comment_test.sh
  tests/long/truffleruby_comment_test.sh
Labels: CI

#5116 Be more specific about selecting a ruby variant
  CHANGELOG.md
  scripts/functions/selector_parse
Labels: bug

#5110 Fix Termux requirements
  CHANGELOG.md
  scripts/functions/requirements/termux
Labels: bug

#5111 Fix invalid brew syntax on requirements check
  CHANGELOG.md
  scripts/functions/requirements/osx_brew
Labels: bug, platform: macos

#5109 Fix GitHub Actions CI
  .github/workflows/specs.yml
  tests/fast/alias_comment_test.sh
  tests/fast/current_and_list_comment_test.sh
  tests/fast/do_comment_test.sh
  tests/fast/gem-bundle_comment_test.sh
  tests/fast/gemfile_comment_test.sh
  tests/fast/gemsets_comment_test.sh
  tests/fast/globalcache_comment_test.sh
  tests/fast/load_ruby-version_comment_test.sh
  tests/fast/remote_comment_test.sh
  tests/fast/ruby-version_comment_test.sh
  tests/fast/rvm-prompt_comment_test.sh
  tests/fast/rvm-shell_comment_test.sh
  tests/fast/rvmrc-create_comment_test.sh
  tests/fast/use_comment_test.sh
  tests/fast/versions.conf_comment_test.sh
  tests/fast/wrapper_comment_test.sh
  tests/long/named_ruby_and_gemsets_comment_test.sh
Labels: CI

#5115 Install ruby-head with ruby 3
  CHANGELOG.md
  scripts/functions/build
Labels: bug

#5117 added rails express patches for MRI 2.6.8, 2.7.4 and 3.0.2
  CHANGELOG.md
  patchsets/ruby/2.6.8/railsexpress
  patchsets/ruby/2.7.4/railsexpress
  patchsets/ruby/3.0.2/railsexpress
Labels: feature

#5119 Fix CI for macOS
  .github/workflows/specs.yml
  CHANGELOG.md
  scripts/functions/build_config
  tests/long/ruby_prepare_mount_comment_test.sh
Labels: CI
