Repository rvm/rvm, pull requests merged in 2021-01, with the labels that each got.

#5023 Requirement glibc-headers obsolete on Fedora 33
  CHANGELOG.md
  scripts/functions/requirements/fedora
  scripts/functions/requirements/fedora_dnf
  scripts/functions/requirements/fedora_yum
Labels: bug

#5026 added rails express patches for 3.0.0 and 3.0-head
  CHANGELOG.md
  patchsets/ruby/3.0.0/railsexpress
  patchsets/ruby/3.0/head/railsexpress
Labels: feature

#5027 Fix unknown command wrappers
  CHANGELOG.md
  scripts/functions/installer
Labels: bug

#5029 Fix fresh installs of RVM
  scripts/functions/installer
Labels: bug

#5028 Replace deprecated test instructions in HACKING.md
  HACKING.md
Labels: documentation

#5031 Ubuntu 20.04 x64 binary for Ruby 3.0.0
  CHANGELOG.md
  config/md5
  config/remote
  config/sha512
Labels: binary

#5032 Recompiling binaries 2.4.10, 2.5.8, 2.6.6, 2.7.1 and 2.7.2 on Ubuntu 20.04.1
  CHANGELOG.md
  config/md5
  config/remote
  config/sha512
Labels: binary

#5030 Fix ruby 3 installation+compilation with rubygems v3.2.3+
  CHANGELOG.md
  scripts/functions/gemset
Labels: bug

#5037 Add TruffleRuby 21.0.0
  CHANGELOG.md
  config/db
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: interpreter: truffleruby
