Repository rvm/rvm, pull requests merged in 2021-11, with the labels that each got.

#5145 Add support for JRuby 9.2.20.0
  CHANGELOG.md
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: interpreter: jruby

#5150 Update keyserver in the docs
  scripts/functions/cli
Labels: bug

#5154 Add frum to RVM alternatives
  docs/alt.md
Labels: documentation

#5155 Add Ruby 3.1.0-preview1
  CHANGELOG.md
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: feature

#5157 Add support for Ruby 2.6.9, 2.7.5, 3.0.3
  CHANGELOG.md
  config/db
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: feature
