Repository rvm/rvm, pull requests merged in 2022-10, with the labels that each got.

#5238 Execute autogen when available
  CHANGELOG.md
  scripts/functions/manage/base_install
Labels: bug

#5258 Add JRuby 9.3.9.0
  CHANGELOG.md
  config/db
  config/known_strings
  config/md5
  config/sha512
Labels: interpreter: jruby

#5247 Allow building ruby 2.7 on Fedora 36
  CHANGELOG.md
  scripts/functions/requirements/fedora
Labels: platform: linux
