Repository rvm/rvm, pull requests merged in 2022-01, with the labels that each got.

#5172 Avoid duplicate package instances when querying pkg-config
  CHANGELOG.md
  scripts/functions/pkg
Labels: bug

#5173 Remove an obsolete patch from the railsexpress patches for Ruby3.1
  CHANGELOG.md
  patchsets/ruby/3.1.0/railsexpress
  patchsets/ruby/3.1/head/railsexpress
Labels: fixed

#5160 Add JRuby 9.2.20.1
  CHANGELOG.md
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: interpreter: jruby

#5163 Add JRuby 9.3.2.0
  CHANGELOG.md
  config/db
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: interpreter: jruby

#5175 Add JRuby 9.3.3.0
  CHANGELOG.md
  config/db
  config/known_strings
  config/md5
  config/sha512
Labels: interpreter: jruby

#5177 Add TruffleRuby 22.0
  CHANGELOG.md
  config/db
  config/known
  config/known_strings
  config/md5
  config/sha512
  rvm-test/long/truffleruby_comment_test.sh
  tests/long/truffleruby_comment_test.sh
Labels: interpreter: truffleruby

#5178 Remove unused duplicate rvm-test/ directory
  HACKING.md
  rvm-test/.versions.conf
  rvm-test/Gemfile
  rvm-test/README.md
  rvm-test/fast/alias_comment_test.sh
  rvm-test/fast/current_and_list_comment_test.sh
  rvm-test/fast/do_comment_test.sh
  rvm-test/fast/env_comment_test.sh
  rvm-test/fast/exports_comment_test.sh
  rvm-test/fast/gem-bundle_comment_test.sh
  rvm-test/fast/gemfile_comment_test.sh
  rvm-test/fast/gemset-copy_comment_test.sh
  rvm-test/fast/gemsets_comment_test.sh
  rvm-test/fast/globalcache_comment_test.sh
  rvm-test/fast/remote_comment_test.sh
  rvm-test/fast/ruby-version_comment_test.sh
  rvm-test/fast/rvm-prompt_comment_test.sh
  rvm-test/fast/rvm-shell_comment_test.sh
  rvm-test/fast/rvmrc-create_comment_test.sh
  rvm-test/fast/rvmrc-warning_comment_test.sh
  rvm-test/fast/rvmrc_comment_test.sh
  rvm-test/fast/use_comment_test.sh
  rvm-test/fast/versions.conf_comment_test.sh
  rvm-test/fast/wrapper_comment_test.sh
  rvm-test/long/jruby_comment_test.sh
  rvm-test/long/named_ruby_and_gemsets_comment_test.sh
  rvm-test/long/rubinius_comment_test.sh
  rvm-test/long/ruby-1.8.7_comment_test.sh
  rvm-test/long/ruby-1.9.3_comment_test.sh
  rvm-test/long/truffleruby_comment_test.sh
  sign-releases.sh
Labels: CI
