Repository rvm/rvm, pull requests merged in 2023-01, with the labels that each got.

#5292 Don't warn about empty GEM_PATH
  CHANGELOG.md
  scripts/rvm
Labels: bug

#5297 Add TruffleRuby 22.3.1
  CHANGELOG.md
  config/db
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: interpreter: truffleruby

#5298 Ubuntu 22.04 binaries for 3.1.3 and 3.2.0
  CHANGELOG.md
  config/md5
  config/remote
  config/sha512
Labels: platform: ubuntu
