Repository rvm/rvm, pull requests merged in 2023-04, with the labels that each got.

#5336 New rubies 2.7.8, 3.0.6, 3.1.4, 3.2.2
  CHANGELOG.md
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: feature

#5339 Ubuntu 22.04 binaries for 3.0.6, 3.1.4 and 3.2.2
  CHANGELOG.md
  config/md5
  config/remote
  config/sha512
Labels: binary

#5340 Install openssl gem for Ruby 3.0.6
  CHANGELOG.md
  gemsets/ruby/3.0.6/global.gems
Labels: bug

#5344 Add TruffleRuby 23.0.0-preview1
  CHANGELOG.md
  config/db
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: interpreter: truffleruby
