Repository rvm/rvm, pull requests merged in 2023-02, with the labels that each got.

#5304 Add JRuby 9.4.1.0
  CHANGELOG.md
  config/db
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: interpreter: jruby

#5306 Add Ruby 3.2.1
  CHANGELOG.md
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: feature

#5307 Ubuntu 22.04 binary for 3.2.1
  CHANGELOG.md
  config/md5
  config/remote
  config/sha512
Labels: binary

#5310 Detect existing Homebrew installs for MacOS arm64e in /opt/homebrew
  CHANGELOG.md
  scripts/functions/requirements/osx_brew
Labels: platform: macos

#5311 added railsexpress patches for ruby 3.2.1
  CHANGELOG.md
  patchsets/ruby/3.2.1/railsexpress
Labels: feature

#5312 Add a patch to fix erratic linker behavior on macOS
  CHANGELOG.md
  patchsets/ruby/3.2.0/railsexpress
  patchsets/ruby/3.2.1/railsexpress
  patchsets/ruby/3.2/head/railsexpress
Labels: fixed, bug

#5308 ruby 3.0.5, 3.1.3, 3.2.1 for Ubuntu 22.10/x86_64 and 22.04/arm64
  CHANGELOG.md
  config/md5
  config/remote
  config/sha512
Labels: binary

#5309 Automatically auto install openssl gem on ruby 2.7 and 3.0
  gem-cache/openssl-3.0.0.gem
  gemsets/ruby/2.7.6/global.gems
  gemsets/ruby/2.7.7/global.gems
  gemsets/ruby/3.0.1/global.gems
  gemsets/ruby/3.0.2/global.gems
  gemsets/ruby/3.0.3/global.gems
  gemsets/ruby/3.0.4/global.gems
  gemsets/ruby/3.0.5/global.gems
Labels: fixed, bug

#5314 Ruby binaries for Centos 7, Amazon 2, Debian 10
  CHANGELOG.md
  config/md5
  config/remote
  config/sha512
Labels: binary

#5313 Fix CI by bumping ancient rubies 2.4.0, 2.4.1, 2.6.6 into 3.0.5, 3.1.2, 3.1.3 in tests
  .github/workflows/specs.yml
  tests/.versions.conf
  tests/fast/alias_comment_test.sh
  tests/fast/current_and_list_comment_test.sh
  tests/fast/do_comment_test.sh
  tests/fast/env_comment_test.sh
  tests/fast/gem-bundle_comment_test.sh
  tests/fast/gemfile_comment_test.sh
  tests/fast/gemset-copy_comment_test.sh
  tests/fast/gemsets_comment_test.sh
  tests/fast/globalcache_comment_test.sh
  tests/fast/load_ruby-version_comment_test.sh
  tests/fast/path_mismatch_comment_test.sh
  tests/fast/ruby-env_comment_test.sh
  tests/fast/ruby-version_comment_test.sh
  tests/fast/rvm-prompt_comment_test.sh
  tests/fast/rvm-shell_comment_test.sh
  tests/fast/rvm-user_comment_test.sh
  tests/fast/rvm_project_rvmrc_comment_test.sh
  tests/fast/rvmrc-create_comment_test.sh
  tests/fast/rvmrc_comment_test.sh
  tests/fast/use_comment_test.sh
  tests/fast/versions.conf_comment_test.sh
  tests/fast/wrapper_comment_test.sh
  tests/long/named_ruby_and_gemsets_comment_test.sh
  tests/long/ruby_prepare_mount_comment_test.sh
Labels: CI

#5221 Fix installing rubies when home directory includes the gemset separator
  CHANGELOG.md
  scripts/functions/gemset
  scripts/functions/selector
Labels: bug

#5248 Add Support for OpenSSL 1.1/3.0 to older ruby versions
  CHANGELOG.md
  patches/ruby/1.8.7/opensslv11x.patch
  patches/ruby/1.8.7/opensslv30.patch
  patches/ruby/1.9.3/opensslv11x.patch
  patches/ruby/1.9.3/opensslv30.patch
  patches/ruby/2.0.0/opensslv11x.patch
  patches/ruby/2.0.0/opensslv30.patch
  patches/ruby/2.5.9/opensslv30.patch
  patchsets/ruby/1.8.7/default
  patchsets/ruby/1.8.7/p374/default
  patchsets/ruby/1.9.3/default
  patchsets/ruby/1.9.3/p551/default
  patchsets/ruby/2.0.0/default
  patchsets/ruby/2.5.9/default
Labels: feature

#5317 Remove reference to Freenode
  CHANGELOG.md
  HACKING.md
Labels: documentation

#5316 Replace keys.gnupg.net in favour of keyserver.ubuntu.com
  CHANGELOG.md
  binscripts/rvm-installer
  binscripts/rvm-installer.asc
Labels: documentation

#5318 Remove reference to subtrees, as we don't use them anymore
  CHANGELOG.md
  CONTRIBUTING.md
Labels: documentation

#5171 Fix non-silent failure on dash
  CHANGELOG.md
  scripts/rvm
Labels: fixed, bug

#5322 Update truffleruby-dev to use builds based on Ubuntu 20.04
  CHANGELOG.md
  scripts/functions/selector_interpreters
Labels: interpreter: truffleruby
