Repository rvm/rvm, pull requests merged in 2024-09, with the labels that each got.

#5498 Detect core count on ARM machines
  CHANGELOG.md
  scripts/functions/build_config
Labels: fixed, bug

#5499 Add support for Ruby 3.3.5
  CHANGELOG.md
  config/db
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: feature

#5500 Fix requirement check for Ubuntu
  CHANGELOG.md
  scripts/functions/requirements/ubuntu
Labels: fixed, bug

#5503 Add TruffleRuby 24.1.0
  CHANGELOG.md
  config/db
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: interpreter: truffleruby
