Repository rvm/rvm, pull requests merged in 2024-06, with the labels that each got.

#5472 Speed up requirements check on Solus
  CHANGELOG.md
  scripts/functions/requirements/solus
Labels: fixed, platform: linux

#5471 Use pkgconf instead of pkg-config in Solus
  CHANGELOG.md
  scripts/functions/requirements/solus
Labels: fixed, platform: linux, bug

#5474 Add support for Ruby 3.3.3
  CHANGELOG.md
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: feature

#5477 Add support for unversioned libncurses-dev packages on newer Debian-like systems
  CHANGELOG.md
  scripts/functions/requirements/debian
  scripts/functions/requirements/deepin
  scripts/functions/requirements/devuan
  scripts/functions/requirements/elementary
  scripts/functions/requirements/kali
  scripts/functions/requirements/mint
  scripts/functions/requirements/trisquel
  scripts/functions/requirements/ubuntu
Labels: platform: ubuntu, platform: debian

#5479 Fix zlib packages for Fedora 40+
  CHANGELOG.md
  scripts/functions/requirements/fedora
  scripts/functions/requirements/fedora_dnf
Labels: platform: fedora

#5480 Require openssl@3 for Ruby 3.2 and 3.3
  .github/workflows/specs.yml
  CHANGELOG.md
  scripts/functions/requirements/osx_brew
Labels: bug
