Repository rvm/rvm, pull requests merged in 2024-05, with the labels that each got.

#5459 Add JRuby 9.4.7.0
  CHANGELOG.md
  config/db
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: interpreter: jruby

#5462 Try to fix macOS CI by pinning to a AMD64 macOS image
  .github/workflows/specs.yml
Labels: CI

#5458 Parallelize GitHub Action jobs in CI
  .github/workflows/specs.yml
  CHANGELOG.md
Labels: CI

#5465 add railsexpress patches for 3.0.7, 3.1.5, 3.2.4 and 3.3.1
  CHANGELOG.md
  patchsets/ruby/3.0.7/railsexpress
  patchsets/ruby/3.1.5/railsexpress
  patchsets/ruby/3.2.4/railsexpress
  patchsets/ruby/3.3.1/railsexpress
Labels: feature

#5466 Add support for Ruby 3.4.0-preview1
  CHANGELOG.md
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: feature

#5470 Add support for Ruby 3.3.2 (#5470)
  CHANGELOG.md
  config/db
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: feature
