Repository rvm/rvm, pull requests merged in 2024-02, with the labels that each got.

#5433 Update location of OpenSSL binary
  CHANGELOG.md
  config/db
Labels: bug

#5425 Fix incorrect example for rvm_make_flags (string changed to array)
  CHANGELOG.md
  examples/rvmrc
Labels: documentation

#5438 Migrate from rvm_io.global.ssl.fastly.net to rvm-io.global.ssl.fastly.net to fix domain fronting report from Fastly
  CHANGELOG.md
  config/db
  config/md5
  config/remote
  config/sha512
Labels: bug

#5439 Add support for Ruby 3.2.3
  CHANGELOG.md
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: feature

#5441 Ubuntu 22.04 amd64 binaries for rubies 3.2.2 and 3.2.3
  CHANGELOG.md
  config/md5
  config/remote
  config/sha512
Labels: binary

#5443 Add JRuby 9.3.14.0 and 9.4.6.0
  CHANGELOG.md
  config/db
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: interpreter: jruby
