Repository rvm/rvm, pull requests merged in 2025-01, with the labels that each got.

#5538 Add JRuby 9.4.10.0
  CHANGELOG.md
  config/db
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: interpreter: jruby

#5540 Add support for ruby 3.3.7
  CHANGELOG.md
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: feature

#5542 ci: update test matrix
  .github/workflows/specs.yml
  tests/fail-in-ci/named_ruby_and_gemsets_comment_test.sh
  tests/fail-in-ci/ruby_prepare_mount_comment_test.sh
  tests/fail-on-3.4/rvm_project_rvmrc_comment_test.sh
  tests/jruby/jruby_comment_test.sh
  tests/legacy/rubinius_comment_test.sh
  tests/legacy/ruby-1.8.7_comment_test.sh
  tests/legacy/ruby-1.9.3_comment_test.sh
  tests/truffleruby/truffleruby_comment_test.sh
Labels: CI

#5543 ci: fix test matrix
  .github/actions/test/action.yml
  .github/workflows/specs.yml
  tests/jruby/jruby_comment_test.sh
  tests/truffleruby/truffleruby_comment_test.sh
Labels: CI

#5539 Add TruffleRuby 24.1.2
  CHANGELOG.md
  config/db
  config/known
  config/known_strings
  config/md5
  config/sha512
Labels: interpreter: truffleruby
